nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: [ '^http://localhost:3000(/[a-zA-Z]+)?' ]
            allow_headers: [ 'Content-Type', 'Authorization' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
            max_age: 3600
